services:
  FoodventenyApp:
    image: ./
    container_name: foodventeny
    ports: 
      - 3333:3333
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports: 
      - 5432:5432