services:
  FoodventenyApp:
    server:
      build: .
      ports: 
        - 3000:3000
    container_name: foodventeny
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD: 'postgres'
      - POSTGRES_USER: 'postgres'
    ports: 
      - 5432:5432
    volumes: 
      - data:/var/lib/postgrsql/data

volumes:
  data: