services:
  foodventeny_db:
      build:
        context: .
        dockerfile: db/Dockerfile
      environment:
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_USER: 'postgres'
      ports: 
        - 5432:5432
      volumes: 
        - data:/var/lib/postgrsql/data

  foodventeny_app:
    build: .
    ports: 
      - 3000:3000
    container_name: foodventeny
    depends_on:
      - foodventeny_db
      # foodventeny_db:
        # condition: service_healthy

volumes:
  data: